{{- if .Values.reporter.enabled }}
{{- $fullname := include "libero-reviewer.fullname" . }}
{{- range $id, $element := .Values.reporter.schedules }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $fullname }}-reporter-{{ $element.name }}
spec:
  schedule: {{ $element.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: reporter-{{ $element.name }}
            image: "{{ $.Values.reporter.image.repository }}:{{ $.Values.reporter.image.tag }}"
            volumeMounts:
            - name: mailheader
              mountPath: "/mail-config"
              readOnly: true
            env:
              - name: RECIPIENT
                value: "{{ $.Values.reporter.recipient }}"
              {{- if $.Values.postgresql.enabled }}
              - name: PGHOST
                value: '{{ include "libero-reviewer.fullname" . }}-postgresql'
              - name: PGUSER
                value: "{{ $.Values.postgresql.postgresqlUsername }}"
              - name: PGPASSWORD
                valueFrom:
                    secretKeyRef:
                      name: {{ $.Values.postgresql.existingSecret | quote }}
                      key: postgresql-password
              - name: PGDATABASE
                value: "{{ $.Values.postgresql.postgresqlDatabase }}"
              {{- else }}
              - name: PGDATABASE
                value: {{ $.Values.database.dbName | quote }}
              - name: PGUSER
                value: {{ $.Values.database.dbUser | quote }}
              - name: PGHOST
                value: {{ $.Values.database.dbHost | quote }}
              - name: PGPASSWORD
                valueFrom:
                    secretKeyRef:
                      name: {{ $.Values.database.dbPasswordSecret | quote }}
                      key: {{ $.Values.database.dbPasswordKey | quote }}
              {{- end }}
              - name: PGPORT
                value: "5432"
              - name: MAILER_HOST
                    secretKeyRef:
                      name: {{ $.Values.reporter.ssmtpSecret | quote }}
                      key: mailerhost
              - name: MAILER_PORT
                    secretKeyRef:
                      name: {{ $.Values.reporter.ssmtpSecret | quote }}
                      key: mailerport
              - name: MAILER_AUTH_USER
                    secretKeyRef:
                      name: {{ $.Values.reporter.ssmtpSecret | quote }}
                      key: user
              - name: MAILER_AUTH_PASS
                    secretKeyRef:
                      name: {{ $.Values.reporter.ssmtpSecret | quote }}
                      key: password
          volumes:
          - name: mailheader
            configMap:
              name: {{ $fullname }}-reporter-mailheader
          restartPolicy: OnFailure
---
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "libero-reviewer.fullname" . }}-reporter-mailheader
data:
  mailheader: |-
    From: {{ .Values.reporter.fromAddress }}
    Subject: {{ .Values.reporter.subjectline }}
    MIME-Version: 1.0
    Content-Type: text/html; charset=utf-8
---
{{- end }}
