{{- if .Values.ingress.enabled -}}
{{- $serviceName := printf "%s-%s" (include "libero-reviewer.fullname" .) ("client") -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "libero-reviewer.fullname" . }}-submission
  labels:
    app.kubernetes.io/name: {{ include "libero-reviewer.name" . }}
    helm.sh/chart: {{ include "libero-reviewer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "{{ div .Values.submission.maxFileSizeInBytes 1000000 }}m"
    nginx.ingress.kubernetes.io/worker-shutdown-timeout: {{ .Values.submission.nginxWorkerTimeoutSeconds }}
    {{- if .Values.submission.enableStickyConnections }}
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-expires: "3600"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "3600"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    nginx.ingress.kubernetes.io/session-cookie-change-on-failure: "true"
    {{- end }}
{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.submission.additionalIngressAnnotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /graphql
            backend:
              serviceName: {{ printf "%s-%s" (include "libero-reviewer.fullname" . ) ("submission") }}
              servicePort: {{ .Values.submission.port}}
          - path: /meca-result
            backend:
              serviceName: {{ printf "%s-%s" (include "libero-reviewer.fullname" . ) ("submission") }}
              servicePort: {{ .Values.submission.port}}
{{- end -}}
