{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "libero-reviewer.fullname" . }}-continuum-adaptor
  labels:
    app.kubernetes.io/name: {{ include "libero-reviewer.name" . }}
    helm.sh/chart: {{ include "libero-reviewer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.continuumAdaptor.additionalIngressAnnotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /auth-login
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ printf "%s-%s" (include "libero-reviewer.fullname" . ) ("continuum-adaptor") }}
                port:
                  number: {{ .Values.continuumAdaptor.port}}
          - path: /auth-logout
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ printf "%s-%s" (include "libero-reviewer.fullname" . ) ("continuum-adaptor") }}
                port:
                  number: {{ .Values.continuumAdaptor.port}}
          - path: /authenticate
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ printf "%s-%s" (include "libero-reviewer.fullname" . ) ("continuum-adaptor") }}
                port:
                  number: {{ .Values.continuumAdaptor.port}}
{{- end -}}
