language: minimal
env:
  global:
    - IMAGE_TAG=$TRAVIS_COMMIT

services:
  - docker

cache: yarn

script:
  - echo "Do something like: make -j 4 $TEST_SUITE"

stages:
  - name: Integration Tests

jobs:
  include:
    - stage: Integration Tests
      name: "API Tests"
      script: echo "Do something here"

if: |
    branch = master OR \
    tag IS present OR \
    type = pull_request
