language: node_js
node_js:
  - 10
env:
  - TEST_SUITE=server_ci
  - TEST_SUITE=client_ci

cache: yarn

script:
  - make $TEST_SUITE

stages:
  - name: Test
  - name: Integration Tests

jobs:
  include:
    - stage: Integration Tests
      name: "API Tests"
      script: make run_api_tests
    - stage: Integration Tests
      name: "Browser Tests"
      script: make run_browser_tests
