language: minimal
env:
  global:
    - IMAGE_TAG=$TRAVIS_COMMIT
  matrix:
    - TEST_SUITE=server_ci
    - TEST_SUITE=client_ci
    - TEST_SUITE=continuum-auth_ci
    - TEST_SUITE=audit_ci

services:
  - docker

cache: yarn

script:
  - make -j 4 $TEST_SUITE

stages:
  - name: Lib Tests
  - name: Test
  - name: Integration Tests
  - name: Deploy Storybook

jobs:
  include:
    - stage: Lib Tests
      name: "Library Tests"
      script: make lib_ci
    - stage: Integration Tests
      name: "API Tests"
      script: make run_api_tests
    - stage: Integration Tests
      name: "Browser Tests"
      script: make run_browser_tests
    - stage: Deploy Storybook
      name: "Deploy Storybook"
      script:
        make build_client_source
        mkdir storybook-static
        docker run -d --name client_storybook__${IMAGE_TAG} libero/reviewer_client_webpack:${IMAGE_TAG}
        docker cp client_storybook__${IMAGE_TAG}:/app/storybook-static/. storybook-static/
        docker stop client_storybook__${IMAGE_TAG}
        docker rm client_storybook__${IMAGE_TAG}

if: |
    branch = master OR \
    tag IS present OR \
    type = pull_request
