language: minimal
env:
  global:
    - IMAGE_TAG=$TRAVIS_COMMIT
  matrix:
    - TEST_SUITE=server_ci
    - TEST_SUITE=continuum-auth_ci
    - TEST_SUITE=audit_ci

services:
  - docker

cache: yarn

script:
  - make -j 4 $TEST_SUITE

stages:
  - name: Lib Tests
  - name: Test
  - name: Integration Tests

jobs:
  include:
    - stage: Integration Tests
      name: "API Tests"
      script: make run_api_tests
if: |
    branch = master OR \
    tag IS present OR \
    type = pull_request
