language: node_js
node_js:
  - 8
  - 10

matrix:
  allowed_failures:
    - node_js: 8
install:
  - cd server
  - yarn
  - yarn build
  - cd ../client
  - yarn

cache: yarn
jobs:
  include:
    - stage: "Test"
      name: "Client Unit Tests"
      script:
        - cd client
        - yarn test
      name: "Client Linting"
      script:
        - cd client
        - yarn lint
      name: "Server Job"
      script:
        - cd server
        - npm run lint
        - npm run test:cov

