version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-2952a7c5-20210615.1224

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-bda527f0-20210614.1546

  submission:
    image: liberoadmin/reviewer-submission:master-2f945b7b-20210616.1223

  client:
    image: liberoadmin/reviewer-client:master-5770b4c1-20210722.1735

  nginx:
    image: nginx:stable-alpine@sha256:f527c86fcced1cc71cb254dd341094ef670cebe1d0daa46f1bbe0a6fd6e3a592
