version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:0.0.6
    ports:
      - "3001:3001"
    healthcheck:
      test: 'echo -e "GET /health\n\n" | nc localhost:3001'
      interval: 2s
      timeout: 10s
      retries: 3
    environment:
      PORT: 3001
      LOGIN_URL: http://nginx:9000/submit
      LOGIN_RETURN_URL: http://nginx:9000/login
      AUTHENTICATION_JWT_SECRET: super_secret_jam
      CONTINUUM_JWT_SECRET: some_secret_from_journal
      CONTINUUM_API_URL: http://reviewer-mocks:3003
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      ELIFE_API_GATEWAY_SECRET: ${ELIFE_API_GATEWAY_SECRET}
    networks:
      - reviewer

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:0.0.5
    ports:
      - "3003:3003"
    healthcheck:
      test: 'echo -e "GET /health\n\n" | nc localhost:3003'
      interval: 2s
      timeout: 10s
      retries: 3
    volumes:
      - ./config/reviewer-mocks/config.json:/etc/reviewer/config.json:z
    networks:
      - reviewer

  submission:
    image: liberoadmin/reviewer-submission:0.0.6
    ports:
      - "3000:3000"
    environment:
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      S3_AWS_ENDPOINT: http://s3:9000
      S3_ACCESS_KEY_ID: minio
      S3_SECRET_ACCESS_KEY: minio123
      S3_FORCE_PATH_STYLE: 'true'
      S3_FILE_BUCKET: test
      MAX_QL_COMPLEXITY: 100
      MAX_QL_DEPTH: 5
      MAX_FILE_SIZE_IN_BYTES: 100000000
      AUTHENTICATION_JWT_SECRET: super_secret_jam
      USER_API_URL: http://continuum-adaptor:3001
      SCIENCE_BEAM_URL: http://reviewer-mocks:3003/science-beam/convert
      SCIENCE_BEAM_TIMEOUT: 20000
      MECA_S3_PATH: 'meca-archive'
      MECA_SFTP_PATH: '/upload'
      MECA_SFTP_HOST: 'sftp'
      MECA_SFTP_USERNAME: 'test'
      MECA_SFTP_PASSWORD: 'test'
      MECA_SFTP_PORT: 22
      MECA_API_KEY: 'someApiKey'
      MECA_EMAIL_PREFIX: '(local)'
      MECA_EMAIL_RECIPIENT: 'libero-reviewer@mailinator.com'
      SEND_MAIL: 'false'
      MAIL_SENDER: 'noreply@elifesciences.org'
      SES_REGION: ''
      SES_SECRET_ACCESS_KEY: ''
      SES_ACCESS_KEY_ID: ''
    healthcheck:
      test: 'echo -e "GET /health\n\n" | nc localhost:3000'
      interval: 2s
      timeout: 10s
      retries: 3
    networks:
      - reviewer

  client:
    image: liberoadmin/reviewer-client:0.0.5
    healthcheck:
      interval: 2s
    networks:
      - reviewer

  nginx:
    image: nginx:stable-alpine@sha256:5ba534070ae1e5e83d52141b11ddced689b476c0001e7205f50979dc0cbdde3d
    networks:
      - reviewer
    ports:
      - '9000:9000'
    volumes:
      - ./config/proxy/nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: 'echo -e "GET /login\n\n" | nc localhost:9000'
      interval: 2s
    depends_on:
      - client
      - submission
      - reviewer-mocks
      - continuum-adaptor

networks:
  reviewer:
    external: true
