version: '3'
services:
  postgres:
    image: liberoadmin/reviewer-xpub-postgres:0.0.6
    ports:
      - "5432:5432"
    networks:
      - reviewer
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 30s
      retries: 10

  s3:
    image: minio/minio:RELEASE.2020-07-22T00-26-33Z
    ports:
      - "9004:9000"
    volumes:
      - ./.data/minio:/data
    networks:
      - reviewer
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 2s
      timeout: 30s
      retries: 10

  s3_create-bucket:
    image: minio/mc:RELEASE.2020-07-17T02-52-20Z
    depends_on:
      - s3
    networks:
      - reviewer
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add submission http://s3:9000 minio minio123;
      /usr/bin/mc rm -r --force submission/test;
      /usr/bin/mc mb submission/test;
      /usr/bin/mc policy set download submission/test;
      /usr/bin/mc policy set public submission/test;
      exit 0;
      "

  sftp:
    image: atmoz/sftp:alpine@sha256:83d6f961689c856c452c5c4abad818b0d572c1f966af812691aeb53640119c35
    networks:
      - reviewer
    volumes:
      - ./.data/ftp:/home
    command: test:test:::upload

networks:
  reviewer:
    external: true
volumes:
  pg-data:
