version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-4cc44cb4-20200818.1249

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-304ed1b7-20200812.1139

  submission:
    image: liberoadmin/reviewer-submission:master-5402d9c1-20200817.1518

  client:
    image: liberoadmin/reviewer-client:master-250f901b-20200723.1330

  nginx:
    image: nginx:stable-alpine@sha256:8853c7e938c2aa5d9d7439e698f0e700f058df8414a83134a09fcbb68bb0707a
