version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-c32cf929-20200527.1606

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-c7e458a2-20200709.1400

  submission:
    image: liberoadmin/reviewer-submission:master-74de2d99-20200625.1629

  client:
    image: liberoadmin/reviewer-client:master-dc3c1741-20200702.1638

  nginx:
    image: nginx:stable-alpine@sha256:676b8117782d9e8c20af8e1b19356f64acc76c981f3a65c66e33a9874877892a
