version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-4d2c50f9-20201214.1327

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-aeb8fa0d-20201214.1329

  submission:
    image: liberoadmin/reviewer-submission:master-f26c406d-20201214.1330

  client:
    image: liberoadmin/reviewer-client:master-405b75cd-20201215.1719

  nginx:
    image: nginx:stable-alpine@sha256:ddcf5d8753a062e297e4448ec332e833f2688a9de667b2a723370a3bc7eb01d5
