version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-55b3b4e7-20201124.1541

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-92b51719-20200914.1053

  submission:
    image: liberoadmin/reviewer-submission:master-f0502e52-20201125.1557

  client:
    image: liberoadmin/reviewer-client:master-12b3dfca-20201120.1212

  nginx:
    image: nginx:stable-alpine@sha256:ddcf5d8753a062e297e4448ec332e833f2688a9de667b2a723370a3bc7eb01d5
