version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-45b91fca-20210309.1019

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-0ecc430c-20210312.1647

  submission:
    image: liberoadmin/reviewer-submission:master-475748ae-20210330.0859

  client:
    image: liberoadmin/reviewer-client:master-004cc6e7-20210413.1116

  nginx:
    image: nginx:stable-alpine@sha256:ec3f6e4587a2053f406b1b4e027c260e82e4e32c256c04e798b52cb4f877e688
