version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-9b060f43-20210105.1404

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-aeb8fa0d-20201214.1329

  submission:
    image: liberoadmin/reviewer-submission:master-f26c406d-20201214.1330

  client:
    image: liberoadmin/reviewer-client:master-371016e5-20210105.1053

  nginx:
    image: nginx:stable-alpine@sha256:da3716611fb965f3fda1f3281882baeb2760ca8bb7317f1d22ed45e75570827b
