version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-bf76dfa4-20220318.0849

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-e34882d7-20220317.1740

  submission:
    image: liberoadmin/reviewer-submission:master-487cab4e-20220707.1541

  client:
    image: liberoadmin/reviewer-client:master-5b5509b8-20220527.1811

  nginx:
    image: nginx:stable-alpine@sha256:0a88a14a264f46562e2d1f318fbf0606bc87e72727528b51613a5e96f483a0f6
