version: '3'
services:
  audit:
    image: node:10
    ports:
      - "${AUDIT_PORT}:3004"
    working_dir: "/service/audit"
    command: ["bash", "-c", "yarn && yarn start:dev"]
    healthcheck:
      test: "curl localhost:3004/health"
      interval: 1m
      timeout: 10s
      retries: 3
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      DB_HOST: ${AUDIT_DB_HOST}
      DB_USERNAME: ${AUDIT_DB_USERNAME}
      DB_PASSWORD: ${AUDIT_DB_PASSWORD}
      DB_PORT: ${AUDIT_DB_PORT}
      DB_NAME: ${AUDIT_DB_NAME}
    volumes:
      - ./audit/:/service/audit/:z
    networks:
      - infra_api
      - infra_rabbit
      - infra_postgres

  continuum-auth:
    image: node:10
    ports:
      - "${AUTHENTICATION_PORT}:3001"
    working_dir: "/service/continuum-auth"
    healthcheck:
      test: "curl localhost:3001/health"
      interval: 1m
      timeout: 10s
      retries: 3
    command: ["bash", "-c", "yarn && yarn start:dev"]
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      AUTHENTICATION_JWT_SECRET: ${AUTHENTICATION_JWT_SECRET}
      CONTINUUM_LOGIN_JWT_SECRET: ${CONTINUUM_LOGIN_JWT_SECRET}
      CONTINUUM_LOGIN_URL: ${CONTINUUM_LOGIN_URL}
      CONTINUUM_LOGIN_PORT: ${CONTINUUM_LOGIN_PORT}
      CLIENT_PORT: ${CLIENT_PORT}
    volumes:
      - ./continuum-auth/:/service/continuum-auth/:z
    networks:
      - infra_api
      - infra_rabbit

  mock-continuum-login:
    image: node:10
    ports:
      - "${CONTINUUM_LOGIN_PORT}:3003"
    working_dir: "/mock-continuum-login"
    healthcheck:
      test: "curl localhost:3003/health"
      interval: 1m
      timeout: 10s
      retries: 3
    command: ["bash", "-c", "yarn && yarn start:dev"]
    environment:
      CONTINUUM_LOGIN_PORT: ${CONTINUUM_LOGIN_PORT}
      CONTINUUM_LOGIN_JWT_SECRET: ${CONTINUUM_LOGIN_JWT_SECRET}
      AUTHENTICATION_URL: ${AUTHENTICATION_URL}
      AUTHENTICATION_PORT: ${AUTHENTICATION_PORT}
    volumes:
      - ./mock-continuum-login/:/mock-continuum-login/:z
    networks:
      - infra_api

  # Domain Services
  server:
    image: node:10
    ports:
      - "${SERVER_PORT}:3000"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DB_HOST: ${SERVER_DB_HOST}
      DB_PORT: ${SERVER_DB_PORT}
      DB_USERNAME: ${SERVER_DB_USERNAME}
      DB_PASSWORD: ${SERVER_DB_PASSWORD}
      DB_NAME: ${SERVER_DB_NAME}
    working_dir: "/service/server"
    healthcheck:
      test: "curl localhost:3000/health"
      interval: 1m
      timeout: 10s
      retries: 3
    command: ["bash", "-c", "yarn && yarn run start:dev"]
    volumes:
      - ./server/:/service/server/:z
    networks:
      - infra_postgres
      - infra_api

networks:
  infra_postgres:
    external:
      name: "infra_postgres"
  infra_api:
    external:
      name: "infra_api"
  infra_rabbit:
    external:
      name: "infra_rabbit"

