version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-c32cf929-20200527.1606

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-a4adebe5-20200618.1056

  submission:
    image: liberoadmin/reviewer-submission:master-259ca88b-20200617.1410

  client:
    image: liberoadmin/reviewer-client:master-a48260fe-20200617.1239

  nginx:
    image: nginx:stable-alpine@sha256:676b8117782d9e8c20af8e1b19356f64acc76c981f3a65c66e33a9874877892a
