version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-4795ef7d-20210614.1529

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-bda527f0-20210614.1546

  submission:
    image: liberoadmin/reviewer-submission:master-69788091-20210511.1029

  client:
    image: liberoadmin/reviewer-client:master-92142591-20210611.1451

  nginx:
    image: nginx:stable-alpine@sha256:4c945e23f40334b2f0e8d6e5040a0ea06fc5c2e0cb355d1af0ae8ba0cdf80ea8
