version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-c32cf929-20200527.1606

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-a4adebe5-20200618.1056

  submission:
    image: liberoadmin/reviewer-submission:master-cab20035-20200618.0926

  client:
    image: liberoadmin/reviewer-client:master-de0065bb-20200618.1623

  nginx:
    image: nginx:stable-alpine@sha256:676b8117782d9e8c20af8e1b19356f64acc76c981f3a65c66e33a9874877892a
