version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-45b91fca-20210309.1019

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-0ecc430c-20210312.1647

  submission:
    image: liberoadmin/reviewer-submission:master-69788091-20210511.1029

  client:
    image: liberoadmin/reviewer-client:master-b7ba238c-20210609.1247

  nginx:
    image: nginx:stable-alpine@sha256:4c945e23f40334b2f0e8d6e5040a0ea06fc5c2e0cb355d1af0ae8ba0cdf80ea8
