version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-c32cf929-20200527.1606

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-9d7cd934-20200616.1343

  submission:
    image: liberoadmin/reviewer-submission:master-8e4645ed-20200616.1045

  client:
    image: liberoadmin/reviewer-client:master-cb378872-20200617.1016

  nginx:
    image: nginx:stable-alpine@sha256:676b8117782d9e8c20af8e1b19356f64acc76c981f3a65c66e33a9874877892a
