version: '3'
services:
  postgres:
    image: liberoadmin/reviewer-xpub-postgres:0.0.2
    ports:
      - "5432:5432"
    networks:
      - infra_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 30s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management@sha256:26737477e6833c4eef9df3065489ebe59d6e2abcc9a46070c8a1561c859b6057
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - infra_rabbit

  etcd1:
    image: gcr.io/etcd-development/etcd:v3.3@sha256:2fb8d6b89baf4e4231c4bcf7b2adc878a2a2dbae41cb6b504d59e59291e7d292
    restart: unless-stopped
    healthcheck:
      test: "etcdctl endpoint health"
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - infra_api
    command: /usr/local/bin/etcd --data-dir=/etcd-data
    environment:
      ETCDCTL_API: 3
      ETCD_DEBUG: 1
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://127.0.0.1:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_ADVERTISE_CLIENT_URLS: http://127.0.0.1:2379
      ETCD_INITIAL_CLUSTER: default=http://127.0.0.1:2380
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - ./.data/etcd:/etcd-data

  s3:
    image: minio/minio:RELEASE.2020-04-23T00-58-49Z
    ports:
      - "9004:9000"
    volumes:
      - ./.data/minio:/data
    networks:
      - infra_api
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 2s
      timeout: 30s
      retries: 10

  s3_create-bucket:
    image: minio/mc:RELEASE.2020-04-25T00-43-23Z
    depends_on:
      - s3
    networks:
      - infra_api
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add submission http://s3:9000 minio minio123;
      /usr/bin/mc rm -r --force submission/test;
      /usr/bin/mc mb submission/test;
      /usr/bin/mc policy set download submission/test;
      /usr/bin/mc policy set public submission/test;
      exit 0;
      "

networks:
  infra_postgres:
    external:
      name: "infra_postgres"
  infra_api:
    external:
      name: "infra_api"
  infra_rabbit:
    external:
      name: "infra_rabbit"
volumes:
  pg-data:
