version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-ab04d32e-20200804.0951

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-39e7d6dc-20200722.0848

  submission:
    image: liberoadmin/reviewer-submission:master-c53ff219-20200730.1520

  client:
    image: liberoadmin/reviewer-client:master-250f901b-20200723.1330

  nginx:
    image: nginx:stable-alpine@sha256:8853c7e938c2aa5d9d7439e698f0e700f058df8414a83134a09fcbb68bb0707a
