version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-2952a7c5-20210615.1224

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-c72f8cc6-20210901.1518

  submission:
    image: liberoadmin/reviewer-submission:master-73d22f45-20211103.1431

  client:
    image: liberoadmin/reviewer-client:master-05bb1099-20210909.0939

  nginx:
    image: nginx:stable-alpine@sha256:672531f89bd685bb59f9ed40cff636898434ec783beec31546fbdc199f1be3ca
