version: '3'
services:
  audit:
    image: liberoadmin/audit:master-48b4c609-20200416.1445
    ports:
      - "3004:3004"
    healthcheck:
      test: 'echo -e "GET /health\n\n" | nc localhost:3004'
      interval: 2s
      timeout: 10s
      retries: 3
    volumes:
      - ./config/audit:/etc/reviewer:z
    networks:
      - infra_api
      - infra_rabbit
      - infra_postgres

  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-fc328369-20200507.1153
    ports:
      - "3001:3001"
    healthcheck:
      test: 'echo -e "GET /health\n\n" | nc localhost:3001'
      interval: 2s
      timeout: 10s
      retries: 3
    environment: 
      PORT: 3001
      RABBITMQ_URL: rabbitmq
      LOGIN_URL: http://localhost:9000/submit
      LOGIN_RETURN_URL: http://localhost:9000/login
      AUTHENTICATION_JWT_SECRET: super_secret_jam
      CONTINUUM_JWT_SECRET: some_secret_from_journal
      CONTINUUM_API_URL: http://reviewer-mocks:3003
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      ELIFE_API_GATEWAY_SECRET: ${ELIFE_API_GATEWAY_SECRET}
    networks:
      - infra_api
      - infra_rabbit
      - infra_postgres

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-dbf41c51-20200505.1239
    ports:
      - "3003:3003"
    healthcheck:
      test: 'echo -e "GET /health\n\n" | nc localhost:3003'
      interval: 2s
      timeout: 10s
      retries: 3
    volumes:
      - ./config/reviewer-mocks:/etc/reviewer:z
    networks:
      - infra_api

  submission:
    image: liberoadmin/reviewer-submission:master-2ce5e1a4-20200507.1158
    environment:
      NEW_RELIC_HOME: ${NEW_RELIC_HOME:-/etc/reviewer}
    healthcheck:
      test: 'echo -e "GET /health\n\n" | nc localhost:3000'
      interval: 2s
      timeout: 10s
      retries: 3
    networks:
      - infra_postgres
      - infra_api

  client:
    image: liberoadmin/reviewer-client:master-a6bcb283-20200507.1456
    healthcheck:
      interval: 2s
    networks:
      - infra_api

  nginx:
    image: nginx:stable-alpine@sha256:0dfc8450deb8c7f06fbaac27e453ac3262df7d3a93639c4e2f48ee39434ec017
    networks:
      - "infra_api"
    ports:
      - '9000:9000'
    volumes:
      - ./config/proxy/nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: 'echo -e "GET /login\n\n" | nc localhost:9000'
      interval: 2s
    depends_on:
      - client
      - submission
      - reviewer-mocks
      - continuum-adaptor


networks:
  infra_postgres:
    external:
      name: "infra_postgres"
  infra_api:
    external:
      name: "infra_api"
  infra_rabbit:
    external:
      name: "infra_rabbit"
