version: '3'
services:
  # Shared packages container
  shared_packages:
    build:
      context: "lib/"
      dockerfile: "Dockerfile.packages"
      args:
        image_tag: ${IMAGE_TAG}
    image: libero/reviewer_shared_packages:${IMAGE_TAG}

  # Server
  server_npm:
    build:
      context: 'server/'
      dockerfile: 'Dockerfile.packages'
      args:
        image_tag: ${IMAGE_TAG}
    image: libero/reviewer_server_packages:${IMAGE_TAG}
    networks:
        - 'reviewer_build'
  server_typescript:
    build:
      context: 'server/'
      dockerfile: "Dockerfile.typescript"
      args:
        image_tag: ${IMAGE_TAG}
    image: libero/reviewer_server_typescript:${IMAGE_TAG}
    depends_on:
      - server_npm
    networks:
        - 'reviewer_build'
  reviewer_server:
    build:
      context: 'server/'
      dockerfile: "Dockerfile.application"
      args:
        image_tag: ${IMAGE_TAG}
    image: libero/reviewer_server:${IMAGE_TAG}
    depends_on:
      - server_npm
      - server_typescript
    networks:
        - 'reviewer_build'

  # Client
  client_npm:
    build:
      context: 'client/'
      dockerfile: 'Dockerfile.packages'
      args:
        image_tag: ${IMAGE_TAG}
    image: libero/reviewer_client_packages:${IMAGE_TAG}
    networks:
        - 'reviewer_build'

  client_webpack:
    build:
      context: 'client/'
      dockerfile: 'Dockerfile.webpack'
      args:
        image_tag: ${IMAGE_TAG}
    image: libero/reviewer_client_webpack:${IMAGE_TAG}
    depends_on:
      - client_npm
    networks:
        - 'reviewer_build'

  reviewer_client:
    build:
      context: 'client/'
      dockerfile: "Dockerfile.application"
      args:
        image_tag: "${IMAGE_TAG}"
    image: libero/reviewer_client:${IMAGE_TAG}
    command: >
      /bin/sh -c
      "envsubt '
      $${CLIENT_PORT}
      $${SERVER_PORT}
      $${CLIENT_API_PROXY_URL}
      '< /etc/nginx/nginx.conf.template
      > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"
    depends_on:
      - client_npm
      - client_webpack
    networks:
        - 'reviewer_build'

  # audit
  audit_npm:
    build:
      context: 'audit/'
      dockerfile: 'dockerfile.packages'
      args:
        image_tag: "${image_tag}"
    image: libero/reviewer_audit_packages:${image_tag}
    networks:
        - 'reviewer_build'
  audit_typescript:
    build:
      context: 'audit/'
      dockerfile: "dockerfile.typescript"
      args:
        image_tag: ${image_tag}
    image: libero/reviewer_audit_typescript:${image_tag}
    depends_on:
      - audit_npm
    networks:
        - 'reviewer_build'
  reviewer_audit:
    build:
      context: 'audit/'
      dockerfile: "dockerfile.application"
      args:
        image_tag: ${image_tag}
    image: libero/reviewer_audit:${image_tag}
    depends_on:
      - audit_npm
      - audit_typescript
    networks:
        - 'reviewer_build'

  # continuum-auth
  continuum-auth_npm:
    build:
      context: 'continuum-auth/'
      dockerfile: 'dockerfile.packages'
      args:
        image_tag: "${image_tag}"
    image: libero/reviewer_continuum-auth_packages:${image_tag}
    networks:
        - 'reviewer_build'
  continuum-auth_typescript:
    build:
      context: 'continuum-auth/'
      dockerfile: "dockerfile.typescript"
      args:
        image_tag: ${image_tag}
    image: libero/reviewer_continuum-auth_typescript:${image_tag}
    depends_on:
      - continuum-auth_npm
    networks:
        - 'reviewer_build'
  reviewer_continuum-auth:
    build:
      context: 'continuum-auth/'
      dockerfile: "dockerfile.application"
      args:
        image_tag: ${image_tag}
    image: libero/reviewer_continuum-auth:${image_tag}
    depends_on:
      - continuum-auth_npm
      - continuum-auth_typescript
    networks:
        - 'reviewer_build'
networks:
  reviewer_build:
    external:
      name: reviewer_build
