version: '3'
services:
  audit:
    image: liberoadmin/audit:0.0.2
    ports:
      - "3004:3004"
    healthcheck:
      test: 'echo -e "GET /health\n\n" | nc localhost:3004'
      interval: 2s
      timeout: 10s
      retries: 3
    volumes:
      - ./config/audit:/etc/reviewer:z
    networks:
      - infra_api
      - infra_rabbit
      - infra_postgres

  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:0.0.3
    ports:
      - "3001:3001"
    healthcheck:
      test: 'echo -e "GET /health\n\n" | nc localhost:3001'
      interval: 2s
      timeout: 10s
      retries: 3
    volumes:
      - ./config/continuum-adaptor:/etc/reviewer:z
    networks:
      - infra_api
      - infra_rabbit
      - infra_postgres

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:0.0.4
    ports:
      - "3003:3003"
    healthcheck:
      test: 'echo -e "GET /health\n\n" | nc localhost:3003'
      interval: 2s
      timeout: 10s
      retries: 3
    volumes:
      - ./config/reviewer-mocks:/etc/reviewer:z
    networks:
      - infra_api

  submission:
    image: liberoadmin/reviewer-submission:0.0.2
    ports:
      - "3000:3000"
    environment:
      NEW_RELIC_HOME: ${NEW_RELIC_HOME:-/etc/reviewer}
    healthcheck:
      test: 'echo -e "GET /health\n\n" | nc localhost:3000'
      interval: 2s
      timeout: 10s
      retries: 3
    volumes:
      - ./config/submission:/etc/reviewer:z
    networks:
      - infra_postgres
      - infra_api

  client:
    image: liberoadmin/reviewer-client:0.0.3
    healthcheck:
      interval: 2s
    ports:
      - "9000:9000"
    volumes:
      - ./config/client:/etc/reviewer:z
    networks:
      - infra_api

networks:
  infra_postgres:
    external:
      name: "infra_postgres"
  infra_api:
    external:
      name: "infra_api"
  infra_rabbit:
    external:
      name: "infra_rabbit"
