version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-c398a21d-20200914.0759

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-92b51719-20200914.1053

  submission:
    image: liberoadmin/reviewer-submission:master-e06cbe54-20201015.1129

  client:
    image: liberoadmin/reviewer-client:master-67aca9cd-20201005.1350

  nginx:
    image: nginx:stable-alpine@sha256:d759c3559a20078d156ccea0e537c274ba335ad6f975b421893ea518258d003a
