version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-4d2c50f9-20201214.1327

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-a5f5c094-20201127.1613

  submission:
    image: liberoadmin/reviewer-submission:master-b97f8efb-20201130.1146

  client:
    image: liberoadmin/reviewer-client:master-9cabbad3-20201203.1221

  nginx:
    image: nginx:stable-alpine@sha256:ddcf5d8753a062e297e4448ec332e833f2688a9de667b2a723370a3bc7eb01d5
