version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-45b91fca-20210309.1019

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-b0f9963c-20210115.1645

  submission:
    image: liberoadmin/reviewer-submission:master-588a450c-20210310.0951

  client:
    image: liberoadmin/reviewer-client:master-8888888c-20210310.1132

  nginx:
    image: nginx:stable-alpine@sha256:34039e81cf9de5f7f92f6280701e92cd51b85fb6b7170c41f6bf8920fcc79f8e
