version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-bf76dfa4-20220318.0849

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-e34882d7-20220317.1740

  submission:
    image: liberoadmin/reviewer-submission:master-487cab4e-20220707.1541

  client:
    image: liberoadmin/reviewer-client:master-bc7361b9-20230222.1222

  nginx:
    image: nginx:stable-alpine@sha256:cc61d734c3045fa64f3d50173e5025e35e0074a29e24559e5ce085b844f6287d
