version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-2952a7c5-20210615.1224

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-c72f8cc6-20210901.1518

  submission:
    image: liberoadmin/reviewer-submission:master-d47dfaac-20220215.1524

  client:
    image: liberoadmin/reviewer-client:master-05bb1099-20210909.0939

  nginx:
    image: nginx:stable-alpine@sha256:74694f2de64c44787a81f0554aa45b281e468c0c58b8665fafceda624d31e556
