version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-34c509c4-20200706.1322

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-3773c70c-20200707.1424

  submission:
    image: liberoadmin/reviewer-submission:master-74de2d99-20200625.1629

  client:
    image: liberoadmin/reviewer-client:master-b498eb4f-20200707.1605

  nginx:
    image: nginx:stable-alpine@sha256:676b8117782d9e8c20af8e1b19356f64acc76c981f3a65c66e33a9874877892a
