version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-bf76dfa4-20220318.0849

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-e34882d7-20220317.1740

  submission:
    image: liberoadmin/reviewer-submission:master-719b1f3d-20220318.0849

  client:
    image: liberoadmin/reviewer-client:master-d9321082-20220318.1619

  nginx:
    image: nginx:stable-alpine@sha256:74694f2de64c44787a81f0554aa45b281e468c0c58b8665fafceda624d31e556
