version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-c32cf929-20200527.1606

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-2786b651-20200527.1401

  submission:
    image: liberoadmin/reviewer-submission:master-dae4c512-20200527.1429

  client:
    image: liberoadmin/reviewer-client:master-49ba041d-20200604.1318

  nginx:
    image: nginx:stable-alpine@sha256:676b8117782d9e8c20af8e1b19356f64acc76c981f3a65c66e33a9874877892a
