version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-49effdc0-20200907.1400

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-b34c5fbc-20200827.1249

  submission:
    image: liberoadmin/reviewer-submission:master-1a910356-20200903.0947

  client:
    image: liberoadmin/reviewer-client:master-23aa60ca-20200902.1452

  nginx:
    image: nginx:stable-alpine@sha256:8853c7e938c2aa5d9d7439e698f0e700f058df8414a83134a09fcbb68bb0707a
