version: '3'
services:

  audit:
    image: liberoadmin/audit:latest
    ports:
      - "${AUDIT_PORT}:3004"
    healthcheck:
      test: "curl localhost:3004/health"
      interval: 1m
      timeout: 10s
      retries: 3
    environment: 
      CONFIG_PATH: /etc/reviewer/config.json
    volumes:
      - ./config/audit:/etc/reviewer:z
    networks:
      - infra_api
      - infra_rabbit
      - infra_postgres

  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:latest
    ports:
      - "${AUTHENTICATION_PORT}:3001"
    healthcheck:
      test: "curl localhost:3001/health"
      interval: 1m
      timeout: 10s
      retries: 3
    volumes:
      - ./config/continuum-adaptor:/etc/reviewer:z
    networks:
      - infra_api
      - infra_rabbit

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:latest
    ports:
      - "${CONTINUUM_LOGIN_PORT}:3003"
    healthcheck:
      test: "curl localhost:3003/health"
      interval: 1m
      timeout: 10s
      retries: 3
    volumes:
      - ./config/reviewer-mocks:/etc/reviewer:z
    networks:
      - infra_api

  server:
    image: liberoadmin/reviewer-submission:latest
    ports:
      - "${SERVER_PORT}:3000"
    environment:
      NEW_RELIC_HOME: ${NEW_RELIC_HOME:-/etc/reviewer}
    healthcheck:
      test: "curl localhost:3000/health"
      interval: 1m
      timeout: 10s
      retries: 3
    volumes:
      - ./config/server:/etc/reviewer:z
    networks:
      - infra_postgres
      - infra_api

  client:
    image: liberoadmin/reviewer-client:latest
    ports:
      - "${CLIENT_PORT}:9000"
    volumes:
      - ./config/client:/etc/reviewer:z
    networks:
      - infra_api
    depends_on: ["server"]

networks:
  infra_postgres:
    external:
      name: "infra_postgres"
  infra_api:
    external:
      name: "infra_api"
  infra_rabbit:
    external:
      name: "infra_rabbit"

