version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-55b3b4e7-20201124.1541

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-a5f5c094-20201127.1613

  submission:
    image: liberoadmin/reviewer-submission:master-b97f8efb-20201130.1146

  client:
    image: liberoadmin/reviewer-client:master-9ee04fbd-20201202.1504

  nginx:
    image: nginx:stable-alpine@sha256:ddcf5d8753a062e297e4448ec332e833f2688a9de667b2a723370a3bc7eb01d5
