version: '3'
services:
  # Server
  server_npm:
    build:
      context: 'server/'
      dockerfile: 'Dockerfile.packages'
    image: liberoadmin/reviewer_server_packages:${IMAGE_TAG}
  server_typescript:
    build:
      context: 'server/'
      dockerfile: "Dockerfile.typescript"
      args:
        image_tag: ${IMAGE_TAG}
    image: liberoadmin/reviewer_server_typescript:${IMAGE_TAG}
    depends_on:
      - server_npm
  reviewer_server:
    build:
      context: 'server/'
      dockerfile: "Dockerfile.application"
      args:
        image_tag: ${IMAGE_TAG}
    image: liberoadmin/reviewer_server:${IMAGE_TAG}
    depends_on:
      - server_npm
      - server_typescript

  # Client
  client_npm:
    build:
      context: 'client/'
      dockerfile: 'Dockerfile.packages'
    image: liberoadmin/reviewer_client_packages:${IMAGE_TAG}
  client_webpack:
    build:
      context: 'client/'
      dockerfile: "Dockerfile.webpack"
      args:
        image_tag: ${IMAGE_TAG}
    image: liberoadmin/reviewer_client_webpack:${IMAGE_TAG}
    depends_on:
      - client_npm
  reviewer_client:
    build:
      context: 'client/'
      dockerfile: "Dockerfile.application"
      args:
        image_tag: ${IMAGE_TAG}
    image: liberoadmin/reviewer_client:${IMAGE_TAG}
    depends_on:
      - client_npm
      - client_webpack
