version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-2952a7c5-20210615.1224

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-bda527f0-20210614.1546

  submission:
    image: liberoadmin/reviewer-submission:master-ccc226e1-20210824.1015

  client:
    image: liberoadmin/reviewer-client:master-55d5cc9d-20210809.1802

  nginx:
    image: nginx:stable-alpine@sha256:bac218df22fef66a173cfa65d0dfa0acca80a3a39df41665be742596977b6c7c
