version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-d4ea3423-20200713.0943

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-c7e458a2-20200709.1400

  submission:
    image: liberoadmin/reviewer-submission:master-22e29ebd-20200715.1048

  client:
    image: liberoadmin/reviewer-client:master-57527a6d-20200715.0900

  nginx:
    image: nginx:stable-alpine@sha256:8853c7e938c2aa5d9d7439e698f0e700f058df8414a83134a09fcbb68bb0707a
