version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-b1ffbcb2-20200720.0816

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-39e7d6dc-20200722.0848

  submission:
    image: liberoadmin/reviewer-submission:master-4feaa866-20200722.0824

  client:
    image: liberoadmin/reviewer-client:master-57527a6d-20200715.0900

  nginx:
    image: nginx:stable-alpine@sha256:8853c7e938c2aa5d9d7439e698f0e700f058df8414a83134a09fcbb68bb0707a
