version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-bf76dfa4-20220318.0849

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-e34882d7-20220317.1740

  submission:
    image: liberoadmin/reviewer-submission:master-f51d281f-20220318.0855

  client:
    image: liberoadmin/reviewer-client:master-ff71137e-20220516.1500

  nginx:
    image: nginx:stable-alpine@sha256:016789c9a2d021b2dcb5e1c724c75ab0a57cc4e8cd7aab7bb28e69fec7c8c4fc
