version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-2952a7c5-20210615.1224

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-bda527f0-20210614.1546

  submission:
    image: liberoadmin/reviewer-submission:master-2f945b7b-20210616.1223

  client:
    image: liberoadmin/reviewer-client:master-71d9c716-20210630.1307

  nginx:
    image: nginx:stable-alpine@sha256:7b801536219e8b3a5dcaf0c5a34c4d4d0514e648905c83105d98c56740eb4f07
