version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-45b91fca-20210309.1019

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-0ecc430c-20210312.1647

  submission:
    image: liberoadmin/reviewer-submission:master-588a450c-20210310.0951

  client:
    image: liberoadmin/reviewer-client:master-bba4a00a-20210319.1755

  nginx:
    image: nginx:stable-alpine@sha256:511cd2f8144e104565dc1a94e04b9588d8c17c61560365d91f44636f77e7e46d
