version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-73b9f4bb-20210115.1716

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-b0f9963c-20210115.1645

  submission:
    image: liberoadmin/reviewer-submission:master-4960d173-20210119.1137

  client:
    image: liberoadmin/reviewer-client:master-ad26952c-20210126.1006

  nginx:
    image: nginx:stable-alpine@sha256:da3716611fb965f3fda1f3281882baeb2760ca8bb7317f1d22ed45e75570827b
