version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-4cc44cb4-20200818.1249

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-b34c5fbc-20200827.1249

  submission:
    image: liberoadmin/reviewer-submission:master-ffaeca1e-20200827.0849

  client:
    image: liberoadmin/reviewer-client:master-23aa60ca-20200902.1452

  nginx:
    image: nginx:stable-alpine@sha256:8853c7e938c2aa5d9d7439e698f0e700f058df8414a83134a09fcbb68bb0707a
