version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-2952a7c5-20210615.1224

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-c72f8cc6-20210901.1518

  submission:
    image: liberoadmin/reviewer-submission:master-2814581a-20210901.1521

  client:
    image: liberoadmin/reviewer-client:master-55d5cc9d-20210809.1802

  nginx:
    image: nginx:stable-alpine@sha256:2012644549052fa07c43b0d19f320c871a25e105d0b23e33645e4f1bcf8fcd97
