
version: '3'
services:
  postgres:
    image: postgres:11
    ports:
      - "5432:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - infra_postgres
    volumes:
      - pg-data:/var/lib/postgresql/data

  server:
    build:
      dockerfile: "./Dockerfile"
      context: "server/"
    ports:
      - "3000:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DB_TYPE: ${DB_TYPE}
      DB_HOST: "postgres"
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    networks:
      - infra_postgres
      - infra_api
    depends_on: ["postgres"]

  client:
    build:
      dockerfile: "./Dockerfile"
      context: "client/"
    ports:
      - "9000:${CLIENT_PORT}"
      - "8080:8080"
    environment:
      CLIENT_PORT: ${CLIENT_PORT}
      CLIENT_API_URL: ${CLIENT_API_URL}
      CLIENT_API_PROXY_URL: "http://server"
      CLIENT_API_PROXY_ENDPOINT: ${CLIENT_API_PROXY_ENDPOINT}
      SERVER_PORT: ${SERVER_PORT}
    networks:
      - infra_api
    depends_on: ["server"]

networks:
  infra_postgres:
  infra_api:

volumes:
  pg-data:
