version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-03471d01-20210108.1252

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-aeb8fa0d-20201214.1329

  submission:
    image: liberoadmin/reviewer-submission:master-477ed98c-20210111.1034

  client:
    image: liberoadmin/reviewer-client:master-79def9fb-20210115.1520

  nginx:
    image: nginx:stable-alpine@sha256:da3716611fb965f3fda1f3281882baeb2760ca8bb7317f1d22ed45e75570827b
