version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-c398a21d-20200914.0759

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-92b51719-20200914.1053

  submission:
    image: liberoadmin/reviewer-submission:master-baea043b-20200930.1454

  client:
    image: liberoadmin/reviewer-client:master-0b5c67ae-20200929.1046

  nginx:
    image: nginx:stable-alpine@sha256:8853c7e938c2aa5d9d7439e698f0e700f058df8414a83134a09fcbb68bb0707a
