version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-b1ffbcb2-20200720.0816

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-39e7d6dc-20200722.0848

  submission:
    image: liberoadmin/reviewer-submission:master-9377b344-20200727.1409

  client:
    image: liberoadmin/reviewer-client:master-250f901b-20200723.1330

  nginx:
    image: nginx:stable-alpine@sha256:8853c7e938c2aa5d9d7439e698f0e700f058df8414a83134a09fcbb68bb0707a
