version: '3'
services:

  audit:
    image: liberoadmin/audit:latest
    ports:
      - "${AUDIT_PORT}:3004"
    healthcheck:
      test: "curl localhost:3004/health"
      interval: 1m
      timeout: 10s
      retries: 3
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      DB_HOST: ${AUDIT_DB_HOST}
      DB_USERNAME: ${AUDIT_DB_USERNAME}
      DB_PASSWORD: ${AUDIT_DB_PASSWORD}
      DB_PORT: ${AUDIT_DB_PORT}
      DB_NAME: ${AUDIT_DB_NAME}
    networks:
      - infra_api
      - infra_rabbit
      - infra_postgres

  continuum-auth:
    image: liberoadmin/continuum-auth:latest
    ports:
      - "${AUTHENTICATION_PORT}:3001"
    healthcheck:
      test: "curl localhost:3001/health"
      interval: 1m
      timeout: 10s
      retries: 3
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      AUTHENTICATION_JWT_SECRET: ${AUTHENTICATION_JWT_SECRET}
      CONTINUUM_LOGIN_JWT_SECRET: ${CONTINUUM_LOGIN_JWT_SECRET}
      CONTINUUM_LOGIN_URL: ${CONTINUUM_LOGIN_URL}
      CONTINUUM_LOGIN_PORT: ${CONTINUUM_LOGIN_PORT}
      CLIENT_PORT: ${CLIENT_PORT}
    networks:
      - infra_api
      - infra_rabbit

  mock-continuum-login:
    image: liberoadmin/mock-continuum-login
    ports:
      - "${CONTINUUM_LOGIN_PORT}:3003"
    healthcheck:
      test: "curl localhost:3003/health"
      interval: 1m
      timeout: 10s
      retries: 3
    environment:
      CONTINUUM_LOGIN_PORT: ${CONTINUUM_LOGIN_PORT}
      CONTINUUM_LOGIN_JWT_SECRET: ${CONTINUUM_LOGIN_JWT_SECRET}
      AUTHENTICATION_URL: ${AUTHENTICATION_URL}
      AUTHENTICATION_PORT: ${AUTHENTICATION_PORT}
    networks:
      - infra_api

  server:
    image: liberoadmin/reviewer-submission:latest
    ports:
      - "${SERVER_PORT}:3000"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DB_HOST: ${SERVER_DB_HOST}
      DB_PORT: ${SERVER_DB_PORT}
      DB_USERNAME: ${SERVER_DB_USERNAME}
      DB_PASSWORD: ${SERVER_DB_PASSWORD}
      DB_NAME: ${SERVER_DB_NAME}
    healthcheck:
      test: "curl localhost:3000/health"
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - infra_postgres
      - infra_api

  client:
    image: liberoadmin/reviewer-client:latest
    ports:
      - "${CLIENT_PORT}:9000"
    environment:
      CLIENT_PORT: ${CLIENT_PORT}
      CLIENT_API_URL: ${CLIENT_API_URL}
      CLIENT_API_PROXY_URL: "http://server"
      CLIENT_API_PROXY_ENDPOINT: ${CLIENT_API_PROXY_ENDPOINT}
      SERVER_PORT: ${SERVER_PORT}
      CONTINUUM_LOGIN_URL: ${CONTINUUM_LOGIN_URL}
      CONTINUUM_LOGIN_PORT: ${CONTINUUM_LOGIN_PORT}
    networks:
      - infra_api
    depends_on: ["server"]

networks:
  infra_postgres:
    external:
      name: "infra_postgres"
  infra_api:
    external:
      name: "infra_api"
  infra_rabbit:
    external:
      name: "infra_rabbit"

