# Default values for libero-reviewer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


submission:
  image:
    repository: liberoadmin/reviewer-submission
    tag: latest
    pullPolicy: Always
  port: 3000
  replicaCount: 1
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
    maxUnavailable: ""

  newRelicHome: /etc/reviewer
  # Sets both an submission internal value as well as ingree max_request
  maxFileSizeInBytes: 100000000

  authenticationJwtSecret: libero-reviewer--auth-jwt

  s3:
    # name of a secret with 'id' and 'access-key' entries
    secret: ""
    bucket: ""
    # Overide the default aws s3 endpoint, set to "" when using aws s3
    endpoint: ""
    forcePathStyle: true

  mail:
    # name of a secret with 'id' and 'access-key' entries
    sesSecret: ""
    sesRegion: ""
    sendMail: false
    sender: "noreply@elifesciences.org"

  sciencebeam:
    convertUrl: "sciencebeam--prod--test-cluster.elifesciences.org/api/convert"
    timeout: 20000

  graphQL:
    maxComplexity: 100
    maxDepth: 5

  meca:
    s3Path: "meca-archive"
    sftpPath: "/upload"
    sftpPort: 22
    sftpSecret: libero-reviewer--sftp
    # Prefix for email subject when MECa import fails, usually "(${environment})"
    emailPrefix: "(staging)"
    emailRecipient: "libero-reviewer@mailinator.com"
    # Name of an existing secret with a 'key' entry
    apiSecret: "libero-reviewer--meca-api"
submissionDbSchema:
  image:
    repository: liberoadmin/reviewer-xpub-postgres
    tag: latest

client:
  image:
    repository: liberoadmin/reviewer-client
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
    maxUnavailable: ""

continuumAdaptor:
  image:
    repository: liberoadmin/continuum-adaptor
    tag: latest
    pullPolicy: Always
  port: 3001
  replicaCount: 1
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
    maxUnavailable: ""
  continuumLoginUrl: "http://continuum.gateway.url/submit"
  continuumApiUrl: "http://continuumtest--gateway.elife.internal"
  # Name of an existing secret with a 'continuumJwtSecret' entry
  continuumJwtSecret: "libero-reviewer--continuum-journal-jwt"
  # Name of an existing secret with a 'token' entry
  elifeApiSecret: "libero-reviewer--elife-api"

# Used if database not managed by this chart i.e. 'postgresql.enabled: false'
database:
  dbHost: ""
  dbUser: ""
  dbName: ""
  # Name of an existing secret
  dbPasswordSecret: ""
  dbPasswordKey: "password"

postgresql:
  enabled: true
  image:
    tag: "11.4.0"
  persistence:
    enabled: false
  postgresqlDatabase: "postgres"
  postgresqlUsername: "postgres"
  existingSecret: "libero-reviewer--postgresql"
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 256Mi
      cpu: 250m

ingress:
  enabled: false
  # applied to _all_ reviewer ingress records
  host: libero-reviewer--staging.domain.tld
  annotations:
  # per ingress annotations
  main:
    annotations:
  login:
    annotations:
  graphql:
    annotations:
  auth:
    annotations:

browsertests:
  image:
    # for the tag we use client.image.tag but strip timestamps
    repository: liberoadmin/reviewer-browsertests
  runPostRelease: false
  testFixture: Minimal
  # baseurl defaults to .Values.ingress.host
  # baseurl: libero-reviewer--staging.domain.tld
