name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  ci-semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Run browsertest container against latest semver images
        run: make test_integration
      - name: Dump logs on failure
        if: failure()
        run: |
          docker-compose -f docker-compose.infra.yml logs
          docker-compose -f docker-compose.yml logs
      - name: Notify slack
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: libero-reviewer-tech
          status: FAILED
          color: danger

  ci-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Run browsertest container against latest master images
        run: make test_integration_master
      - name: Dump logs on failure
        if: failure()
        run: |
          docker-compose -f docker-compose.infra.yml logs
          docker-compose -f docker-compose.master.yml logs
      - name: Notify slack
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: libero-reviewer-tech
          status: FAILED
          color: warning

  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0-rc.1
        with:
          command: lint
      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0-alpha.3
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'
      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0-rc.1
        with:
          command: install
          config: ct.yaml
